package com.mall.parking.carwash.api.bean;

import java.io.Serializable;
import java.util.Date;

public class CarWash implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.id
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.member_id
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.plate_no
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private String plateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.ticket_code
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private String ticketCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.create_by
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.create_date
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.update_by
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.update_date
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.remark
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.version
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_wash.state
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.id
     *
     * @return the value of car_wash.id
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.id
     *
     * @param id the value for car_wash.id
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.member_id
     *
     * @return the value of car_wash.member_id
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.member_id
     *
     * @param memberId the value for car_wash.member_id
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.plate_no
     *
     * @return the value of car_wash.plate_no
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public String getPlateNo() {
        return plateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.plate_no
     *
     * @param plateNo the value for car_wash.plate_no
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setPlateNo(String plateNo) {
        this.plateNo = plateNo == null ? null : plateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.ticket_code
     *
     * @return the value of car_wash.ticket_code
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public String getTicketCode() {
        return ticketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.ticket_code
     *
     * @param ticketCode the value for car_wash.ticket_code
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setTicketCode(String ticketCode) {
        this.ticketCode = ticketCode == null ? null : ticketCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.create_by
     *
     * @return the value of car_wash.create_by
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.create_by
     *
     * @param createBy the value for car_wash.create_by
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.create_date
     *
     * @return the value of car_wash.create_date
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.create_date
     *
     * @param createDate the value for car_wash.create_date
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.update_by
     *
     * @return the value of car_wash.update_by
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.update_by
     *
     * @param updateBy the value for car_wash.update_by
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.update_date
     *
     * @return the value of car_wash.update_date
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.update_date
     *
     * @param updateDate the value for car_wash.update_date
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.remark
     *
     * @return the value of car_wash.remark
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.remark
     *
     * @param remark the value for car_wash.remark
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.version
     *
     * @return the value of car_wash.version
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.version
     *
     * @param version the value for car_wash.version
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_wash.state
     *
     * @return the value of car_wash.state
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_wash.state
     *
     * @param state the value for car_wash.state
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}