package com.mall.parking.charging.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.mall.parking.charging.entity.ChargingRule;
import com.mall.parking.charging.entity.ChargingRuleExample;

@Mapper
public interface ChargingRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    long countByExample(ChargingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int deleteByExample(ChargingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int insert(ChargingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int insertSelective(ChargingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    List<ChargingRule> selectByExample(ChargingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    ChargingRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") ChargingRule record, @Param("example") ChargingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByExample(@Param("record") ChargingRule record, @Param("example") ChargingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByPrimaryKeySelective(ChargingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charging_rule
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByPrimaryKey(ChargingRule record);
}