package com.mall.parking.charging.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mall.parking.charging.entity.Entrance;
import com.mall.parking.charging.entity.EntranceExample;

public interface EntranceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    long countByExample(EntranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int deleteByExample(EntranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int insert(Entrance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int insertSelective(Entrance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    List<Entrance> selectByExample(EntranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    Entrance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Entrance record, @Param("example") EntranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByExample(@Param("record") Entrance record, @Param("example") EntranceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByPrimaryKeySelective(Entrance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrance
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByPrimaryKey(Entrance record);
}