package com.mall.parking.charging.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mall.parking.charging.entity.Exists;
import com.mall.parking.charging.entity.ExistsExample;

public interface ExistsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    long countByExample(ExistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int deleteByExample(ExistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int insert(Exists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int insertSelective(Exists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    List<Exists> selectByExample(ExistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    Exists selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Exists record, @Param("example") ExistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByExample(@Param("record") Exists record, @Param("example") ExistsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByPrimaryKeySelective(Exists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exists
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    int updateByPrimaryKey(Exists record);
}