package com.mall.parking.common.entity;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phone
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.birth
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private String birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.full_name
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_by
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_date
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_by
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_date
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.remark
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.version
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.state
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phone
     *
     * @return the value of member.phone
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phone
     *
     * @param phone the value for member.phone
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.birth
     *
     * @return the value of member.birth
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.birth
     *
     * @param birth the value for member.birth
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.full_name
     *
     * @return the value of member.full_name
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.full_name
     *
     * @param fullName the value for member.full_name
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_by
     *
     * @return the value of member.create_by
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_by
     *
     * @param createBy the value for member.create_by
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_date
     *
     * @return the value of member.create_date
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_date
     *
     * @param createDate the value for member.create_date
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_by
     *
     * @return the value of member.update_by
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_by
     *
     * @param updateBy the value for member.update_by
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_date
     *
     * @return the value of member.update_date
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_date
     *
     * @param updateDate the value for member.update_date
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.remark
     *
     * @return the value of member.remark
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.remark
     *
     * @param remark the value for member.remark
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.version
     *
     * @return the value of member.version
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.version
     *
     * @param version the value for member.version
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.state
     *
     * @return the value of member.state
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.state
     *
     * @param state the value for member.state
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}