package com.mall.parking.card.mapper;

import com.mall.parking.card.entity.Exchange;
import com.mall.parking.card.entity.ExchangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    long countByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int deleteByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int insert(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int insertSelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    List<Exchange> selectByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    Exchange selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") Exchange record, @Param("example") ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByExample(@Param("record") Exchange record, @Param("example") ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByPrimaryKeySelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByPrimaryKey(Exchange record);
}