package com.mall.parking.card.mapper;

import com.mall.parking.card.entity.MemberSign;
import com.mall.parking.card.entity.MemberSignExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    long countByExample(MemberSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int deleteByExample(MemberSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int insert(MemberSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int insertSelective(MemberSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    List<MemberSign> selectByExample(MemberSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    MemberSign selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemberSign record, @Param("example") MemberSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByExample(@Param("record") MemberSign record, @Param("example") MemberSignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByPrimaryKeySelective(MemberSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_sign
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByPrimaryKey(MemberSign record);
}