package com.mall.parking.card.mapper;

import com.mall.parking.card.entity.MemberCard;
import com.mall.parking.card.entity.MemberCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    long countByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int deleteByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int insert(MemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int insertSelective(MemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    List<MemberCard> selectByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    MemberCard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemberCard record, @Param("example") MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByExample(@Param("record") MemberCard record, @Param("example") MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByPrimaryKeySelective(MemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    int updateByPrimaryKey(MemberCard record);
}