package com.mall.parking.card.entity;

import java.util.Date;

public class MemberSign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.id
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.member_id
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.cnt
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private Integer cnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.ctype
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private Integer ctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.create_by
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.create_date
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.update_by
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.update_date
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.remark
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.version
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sign.state
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.id
     *
     * @return the value of member_sign.id
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.id
     *
     * @param id the value for member_sign.id
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.member_id
     *
     * @return the value of member_sign.member_id
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.member_id
     *
     * @param memberId the value for member_sign.member_id
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.cnt
     *
     * @return the value of member_sign.cnt
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.cnt
     *
     * @param cnt the value for member_sign.cnt
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.ctype
     *
     * @return the value of member_sign.ctype
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.ctype
     *
     * @param ctype the value for member_sign.ctype
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.create_by
     *
     * @return the value of member_sign.create_by
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.create_by
     *
     * @param createBy the value for member_sign.create_by
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.create_date
     *
     * @return the value of member_sign.create_date
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.create_date
     *
     * @param createDate the value for member_sign.create_date
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.update_by
     *
     * @return the value of member_sign.update_by
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.update_by
     *
     * @param updateBy the value for member_sign.update_by
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.update_date
     *
     * @return the value of member_sign.update_date
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.update_date
     *
     * @param updateDate the value for member_sign.update_date
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.remark
     *
     * @return the value of member_sign.remark
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.remark
     *
     * @param remark the value for member_sign.remark
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.version
     *
     * @return the value of member_sign.version
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.version
     *
     * @param version the value for member_sign.version
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sign.state
     *
     * @return the value of member_sign.state
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sign.state
     *
     * @param state the value for member_sign.state
     *
     * @mbg.generated Thu Jan 02 14:33:41 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}