package com.mall.parking.card.entity;

import java.util.Date;

public class MemberCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.id
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.cur_qty
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private String curQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.create_by
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.create_date
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.update_by
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.update_date
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.remark
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.version
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.state
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.id
     *
     * @return the value of member_card.id
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.id
     *
     * @param id the value for member_card.id
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.cur_qty
     *
     * @return the value of member_card.cur_qty
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public String getCurQty() {
        return curQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.cur_qty
     *
     * @param curQty the value for member_card.cur_qty
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setCurQty(String curQty) {
        this.curQty = curQty == null ? null : curQty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.create_by
     *
     * @return the value of member_card.create_by
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.create_by
     *
     * @param createBy the value for member_card.create_by
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.create_date
     *
     * @return the value of member_card.create_date
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.create_date
     *
     * @param createDate the value for member_card.create_date
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.update_by
     *
     * @return the value of member_card.update_by
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.update_by
     *
     * @param updateBy the value for member_card.update_by
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.update_date
     *
     * @return the value of member_card.update_date
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.update_date
     *
     * @param updateDate the value for member_card.update_date
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.remark
     *
     * @return the value of member_card.remark
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.remark
     *
     * @param remark the value for member_card.remark
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.version
     *
     * @return the value of member_card.version
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.version
     *
     * @param version the value for member_card.version
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.state
     *
     * @return the value of member_card.state
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.state
     *
     * @param state the value for member_card.state
     *
     * @mbg.generated Tue Dec 31 17:03:58 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}