package com.mall.parking.charging.entity;

import java.util.Date;

public class ChargingRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.start
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Integer start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.end
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Integer end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.fee
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Float fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.create_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.create_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.update_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.update_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.remark
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.version
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charging_rule.state
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.id
     *
     * @return the value of charging_rule.id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.id
     *
     * @param id the value for charging_rule.id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.start
     *
     * @return the value of charging_rule.start
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Integer getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.start
     *
     * @param start the value for charging_rule.start
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setStart(Integer start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.end
     *
     * @return the value of charging_rule.end
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Integer getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.end
     *
     * @param end the value for charging_rule.end
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setEnd(Integer end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.fee
     *
     * @return the value of charging_rule.fee
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Float getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.fee
     *
     * @param fee the value for charging_rule.fee
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setFee(Float fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.create_by
     *
     * @return the value of charging_rule.create_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.create_by
     *
     * @param createBy the value for charging_rule.create_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.create_date
     *
     * @return the value of charging_rule.create_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.create_date
     *
     * @param createDate the value for charging_rule.create_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.update_by
     *
     * @return the value of charging_rule.update_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.update_by
     *
     * @param updateBy the value for charging_rule.update_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.update_date
     *
     * @return the value of charging_rule.update_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.update_date
     *
     * @param updateDate the value for charging_rule.update_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.remark
     *
     * @return the value of charging_rule.remark
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.remark
     *
     * @param remark the value for charging_rule.remark
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.version
     *
     * @return the value of charging_rule.version
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.version
     *
     * @param version the value for charging_rule.version
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charging_rule.state
     *
     * @return the value of charging_rule.state
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charging_rule.state
     *
     * @param state the value for charging_rule.state
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}