package com.mall.parking.charging.entity;

import java.util.Date;

public class Exists {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.member_id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.brake_id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String brakeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.plate_no
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String plateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.create_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.create_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.update_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.update_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.remark
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.version
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exists.state
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.id
     *
     * @return the value of exists.id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.id
     *
     * @param id the value for exists.id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.member_id
     *
     * @return the value of exists.member_id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.member_id
     *
     * @param memberId the value for exists.member_id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.brake_id
     *
     * @return the value of exists.brake_id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getBrakeId() {
        return brakeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.brake_id
     *
     * @param brakeId the value for exists.brake_id
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setBrakeId(String brakeId) {
        this.brakeId = brakeId == null ? null : brakeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.plate_no
     *
     * @return the value of exists.plate_no
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getPlateNo() {
        return plateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.plate_no
     *
     * @param plateNo the value for exists.plate_no
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setPlateNo(String plateNo) {
        this.plateNo = plateNo == null ? null : plateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.create_by
     *
     * @return the value of exists.create_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.create_by
     *
     * @param createBy the value for exists.create_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.create_date
     *
     * @return the value of exists.create_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.create_date
     *
     * @param createDate the value for exists.create_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.update_by
     *
     * @return the value of exists.update_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.update_by
     *
     * @param updateBy the value for exists.update_by
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.update_date
     *
     * @return the value of exists.update_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.update_date
     *
     * @param updateDate the value for exists.update_date
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.remark
     *
     * @return the value of exists.remark
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.remark
     *
     * @param remark the value for exists.remark
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.version
     *
     * @return the value of exists.version
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.version
     *
     * @param version the value for exists.version
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exists.state
     *
     * @return the value of exists.state
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exists.state
     *
     * @param state the value for exists.state
     *
     * @mbg.generated Sat Jan 04 07:17:32 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}