package com.mall.parking.finance.entity;

import java.util.Date;

public class MonthCardRecharge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.id
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.card_no
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.member_id
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.amount
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private Float amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.create_by
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.create_date
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.update_by
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.update_date
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.remark
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.version
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_card_recharge.state
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.id
     *
     * @return the value of month_card_recharge.id
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.id
     *
     * @param id the value for month_card_recharge.id
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.card_no
     *
     * @return the value of month_card_recharge.card_no
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.card_no
     *
     * @param cardNo the value for month_card_recharge.card_no
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.member_id
     *
     * @return the value of month_card_recharge.member_id
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.member_id
     *
     * @param memberId the value for month_card_recharge.member_id
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.amount
     *
     * @return the value of month_card_recharge.amount
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.amount
     *
     * @param amount the value for month_card_recharge.amount
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.create_by
     *
     * @return the value of month_card_recharge.create_by
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.create_by
     *
     * @param createBy the value for month_card_recharge.create_by
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.create_date
     *
     * @return the value of month_card_recharge.create_date
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.create_date
     *
     * @param createDate the value for month_card_recharge.create_date
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.update_by
     *
     * @return the value of month_card_recharge.update_by
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.update_by
     *
     * @param updateBy the value for month_card_recharge.update_by
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.update_date
     *
     * @return the value of month_card_recharge.update_date
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.update_date
     *
     * @param updateDate the value for month_card_recharge.update_date
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.remark
     *
     * @return the value of month_card_recharge.remark
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.remark
     *
     * @param remark the value for month_card_recharge.remark
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.version
     *
     * @return the value of month_card_recharge.version
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.version
     *
     * @param version the value for month_card_recharge.version
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_card_recharge.state
     *
     * @return the value of month_card_recharge.state
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_card_recharge.state
     *
     * @param state the value for month_card_recharge.state
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}