package com.mall.parking.resource.entity;

import java.util.Date;

public class Brake {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.code
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.desc
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brake.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.id
     *
     * @return the value of brake.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.id
     *
     * @param id the value for brake.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.code
     *
     * @return the value of brake.code
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.code
     *
     * @param code the value for brake.code
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.desc
     *
     * @return the value of brake.desc
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.desc
     *
     * @param desc the value for brake.desc
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.create_by
     *
     * @return the value of brake.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.create_by
     *
     * @param createBy the value for brake.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.create_date
     *
     * @return the value of brake.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.create_date
     *
     * @param createDate the value for brake.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.update_by
     *
     * @return the value of brake.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.update_by
     *
     * @param updateBy the value for brake.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.update_date
     *
     * @return the value of brake.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.update_date
     *
     * @param updateDate the value for brake.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.remark
     *
     * @return the value of brake.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.remark
     *
     * @param remark the value for brake.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.version
     *
     * @return the value of brake.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.version
     *
     * @param version the value for brake.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brake.state
     *
     * @return the value of brake.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brake.state
     *
     * @param state the value for brake.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}