package com.mall.parking.resource.entity;

import java.util.Date;

public class StallParked {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.stall_id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String stallId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.plate_no
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String plateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.mtype
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Integer mtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall_parked.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.id
     *
     * @return the value of stall_parked.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.id
     *
     * @param id the value for stall_parked.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.stall_id
     *
     * @return the value of stall_parked.stall_id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getStallId() {
        return stallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.stall_id
     *
     * @param stallId the value for stall_parked.stall_id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setStallId(String stallId) {
        this.stallId = stallId == null ? null : stallId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.plate_no
     *
     * @return the value of stall_parked.plate_no
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getPlateNo() {
        return plateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.plate_no
     *
     * @param plateNo the value for stall_parked.plate_no
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setPlateNo(String plateNo) {
        this.plateNo = plateNo == null ? null : plateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.mtype
     *
     * @return the value of stall_parked.mtype
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Integer getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.mtype
     *
     * @param mtype the value for stall_parked.mtype
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setMtype(Integer mtype) {
        this.mtype = mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.create_by
     *
     * @return the value of stall_parked.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.create_by
     *
     * @param createBy the value for stall_parked.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.create_date
     *
     * @return the value of stall_parked.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.create_date
     *
     * @param createDate the value for stall_parked.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.update_by
     *
     * @return the value of stall_parked.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.update_by
     *
     * @param updateBy the value for stall_parked.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.update_date
     *
     * @return the value of stall_parked.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.update_date
     *
     * @param updateDate the value for stall_parked.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.remark
     *
     * @return the value of stall_parked.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.remark
     *
     * @param remark the value for stall_parked.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.version
     *
     * @return the value of stall_parked.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.version
     *
     * @param version the value for stall_parked.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall_parked.state
     *
     * @return the value of stall_parked.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall_parked.state
     *
     * @param state the value for stall_parked.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}