package com.mall.parking.resource.entity;

import java.util.Date;

public class Stall {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.code
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.is_parked
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Integer isParked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stall.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.id
     *
     * @return the value of stall.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.id
     *
     * @param id the value for stall.id
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.code
     *
     * @return the value of stall.code
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.code
     *
     * @param code the value for stall.code
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.is_parked
     *
     * @return the value of stall.is_parked
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Integer getIsParked() {
        return isParked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.is_parked
     *
     * @param isParked the value for stall.is_parked
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setIsParked(Integer isParked) {
        this.isParked = isParked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.create_by
     *
     * @return the value of stall.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.create_by
     *
     * @param createBy the value for stall.create_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.create_date
     *
     * @return the value of stall.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.create_date
     *
     * @param createDate the value for stall.create_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.update_by
     *
     * @return the value of stall.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.update_by
     *
     * @param updateBy the value for stall.update_by
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.update_date
     *
     * @return the value of stall.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.update_date
     *
     * @param updateDate the value for stall.update_date
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.remark
     *
     * @return the value of stall.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.remark
     *
     * @param remark the value for stall.remark
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.version
     *
     * @return the value of stall.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.version
     *
     * @param version the value for stall.version
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stall.state
     *
     * @return the value of stall.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stall.state
     *
     * @param state the value for stall.state
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}