package com.mall.parking.member.mapper;

import com.mall.parking.member.entity.Vehicle;
import com.mall.parking.member.entity.VehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    long countByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    int deleteByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    int insertSelective(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    List<Vehicle> selectByExample(VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    Vehicle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") Vehicle record, @Param("example") VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    int updateByExample(@Param("record") Vehicle record, @Param("example") VehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    int updateByPrimaryKeySelective(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated Mon Dec 30 14:08:29 CST 2019
     */
    int updateByPrimaryKey(Vehicle record);
}