package com.mall.parking.resource.mapper;

import com.mall.parking.resource.entity.Stall;
import com.mall.parking.resource.entity.StallExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    long countByExample(StallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    int deleteByExample(StallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    int insert(Stall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    int insertSelective(Stall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    List<Stall> selectByExample(StallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    Stall selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Stall record, @Param("example") StallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    int updateByExample(@Param("record") Stall record, @Param("example") StallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    int updateByPrimaryKeySelective(Stall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stall
     *
     * @mbg.generated Mon Jan 06 15:16:46 CST 2020
     */
    int updateByPrimaryKey(Stall record);
}