package com.mall.parking.carwash.serv.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.mall.parking.carwash.api.bean.CarWash;
import com.mall.parking.carwash.serv.bean.CarWashExample;


public interface CarWashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    long countByExample(CarWashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    int deleteByExample(CarWashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    int insert(CarWash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    int insertSelective(CarWash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    List<CarWash> selectByExample(CarWashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    CarWash selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") CarWash record, @Param("example") CarWashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    int updateByExample(@Param("record") CarWash record, @Param("example") CarWashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    int updateByPrimaryKeySelective(CarWash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_wash
     *
     * @mbg.generated Thu Jan 09 20:58:51 CST 2020
     */
    int updateByPrimaryKey(CarWash record);
}