package com.mall.parking.finance.mapper;

import com.mall.parking.finance.entity.Billing;
import com.mall.parking.finance.entity.BillingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    long countByExample(BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    int deleteByExample(BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    int insert(Billing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    int insertSelective(Billing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    List<Billing> selectByExample(BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    Billing selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") Billing record, @Param("example") BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    int updateByExample(@Param("record") Billing record, @Param("example") BillingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    int updateByPrimaryKeySelective(Billing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billing
     *
     * @mbg.generated Mon Jan 06 13:07:41 CST 2020
     */
    int updateByPrimaryKey(Billing record);
}