package com.mall.parking.common.bean;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mtype
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private String mtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mcontent
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private String mcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.member_id
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_by
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_date
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_by
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_date
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.remark
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.version
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.state
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mtype
     *
     * @return the value of message.mtype
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public String getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mtype
     *
     * @param mtype the value for message.mtype
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setMtype(String mtype) {
        this.mtype = mtype == null ? null : mtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mcontent
     *
     * @return the value of message.mcontent
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public String getMcontent() {
        return mcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mcontent
     *
     * @param mcontent the value for message.mcontent
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setMcontent(String mcontent) {
        this.mcontent = mcontent == null ? null : mcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.member_id
     *
     * @return the value of message.member_id
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.member_id
     *
     * @param memberId the value for message.member_id
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_by
     *
     * @return the value of message.create_by
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_by
     *
     * @param createBy the value for message.create_by
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_date
     *
     * @return the value of message.create_date
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_date
     *
     * @param createDate the value for message.create_date
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_by
     *
     * @return the value of message.update_by
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_by
     *
     * @param updateBy the value for message.update_by
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_date
     *
     * @return the value of message.update_date
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_date
     *
     * @param updateDate the value for message.update_date
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.remark
     *
     * @return the value of message.remark
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.remark
     *
     * @param remark the value for message.remark
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.version
     *
     * @return the value of message.version
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.version
     *
     * @param version the value for message.version
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.state
     *
     * @return the value of message.state
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.state
     *
     * @param state the value for message.state
     *
     * @mbg.generated Mon Jan 06 17:46:49 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}